sylius_twig_hooks:
    hooks:
        'sylius_admin.payment_method.create.content.form.sections.general':
            zones:
                template: '@ThreeBRSSyliusPaymentRestrictionPlugin/bundles/SyliusAdminBundle/_form.html.twig'
                priority: 0
        'sylius_admin.payment_method.update.content.form.sections.general':
            zones:
                template: '@ThreeBRSSyliusPaymentRestrictionPlugin/bundles/SyliusAdminBundle/_form.html.twig'
                priority: 0
            
            